# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Release On Tag

on:
  push:
    tags:
      - "v*.*.*"


jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Build
      run: CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags="-s -w" -o sshmanager ./ssm

    - name: Test
      run: go test -v ./...

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.3
      with:
        name: binary
        path: |
          sshmanager

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download Build Artifact
        uses: actions/download-artifact@v2
        with:
          name: binary
          path: sshmanager

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          files: ./sshmanager/sshmanager

permissions:
  contents: write
